// Generated by: supabase gen types typescript --local > types/database.ts
// Run this after `supabase db reset` to keep in sync with migrations.
// This stub is replaced on first local Supabase setup.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type UserRole = 'artist' | 'organizer' | 'both' | 'attendee' | 'admin';
export type PriceUnit = 'per_hour' | 'per_event' | 'per_day';
export type ArtistCategory =
  | 'dj'
  | 'fire_led_dancer'
  | 'magician'
  | 'emcee'
  | 'photographer'
  | 'instrumentalist'
  | 'singer_band'
  | 'lifestyle_painter'
  | 'model'
  | 'drone_specialist';
export type PortfolioType = 'image' | 'video';
export type BookingStatus =
  | 'requested'
  | 'countered'
  | 'accepted'
  | 'declined'
  | 'paid'
  | 'in_progress'
  | 'completed'
  | 'cancelled'
  | 'disputed';
export type PaymentStatus = 'pending' | 'held' | 'released' | 'refunded' | 'failed';
export type ArtistApplicationStatus = 'draft' | 'submitted' | 'approved' | 'rejected';

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          role: UserRole | null;
          display_name: string | null;
          phone: string | null;
          phone_verified_at: string | null;
          email: string | null;
          avatar_url: string | null;
          city: string | null;
          country: string;
          notification_prefs: Json;
          expo_push_token: string | null;
          setup_complete: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string };
        Update: Partial<Database['public']['Tables']['profiles']['Row']>;
      };
      artist_profiles: {
        Row: {
          profile_id: string;
          bio: string | null;
          years_experience: number | null;
          languages: string[] | null;
          base_price: number | null;
          price_unit: PriceUnit | null;
          currency: string;
          service_radius_km: number | null;
          is_verified: boolean;
          application_status: ArtistApplicationStatus;
          application_submitted_at: string | null;
          total_bookings: number;
          avg_rating: number | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Partial<Database['public']['Tables']['artist_profiles']['Row']> & {
          profile_id: string;
        };
        Update: Partial<Database['public']['Tables']['artist_profiles']['Row']>;
      };
      artist_categories: {
        Row: { artist_id: string; category: ArtistCategory };
        Insert: { artist_id: string; category: ArtistCategory };
        Update: never;
      };
      portfolio_items: {
        Row: {
          id: string;
          artist_id: string;
          type: PortfolioType;
          storage_path: string;
          caption: string | null;
          sort_order: number;
          created_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database['public']['Tables']['portfolio_items']['Row'],
          'id' | 'created_at' | 'deleted_at'
        >;
        Update: Partial<Database['public']['Tables']['portfolio_items']['Row']>;
      };
      availability_blocks: {
        Row: {
          id: string;
          artist_id: string;
          start_date: string;
          end_date: string;
          reason: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['availability_blocks']['Row'],
          'id' | 'created_at'
        >;
        Update: Partial<Database['public']['Tables']['availability_blocks']['Row']>;
      };
      bookings: {
        Row: {
          id: string;
          organizer_id: string;
          artist_id: string;
          event_date: string;
          event_end: string;
          location_text: string | null;
          location_lat: number | null;
          location_lng: number | null;
          event_type: string | null;
          brief: string | null;
          proposed_amount: number | null;
          final_amount: number | null;
          currency: string;
          status: BookingStatus;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<
          Database['public']['Tables']['bookings']['Row'],
          'id' | 'created_at' | 'updated_at' | 'deleted_at'
        >;
        Update: Partial<Database['public']['Tables']['bookings']['Row']>;
      };
      payments: {
        Row: {
          id: string;
          booking_id: string;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          amount: number;
          platform_fee: number | null;
          artist_payout: number | null;
          currency: string;
          status: PaymentStatus;
          held_at: string | null;
          released_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database['public']['Tables']['payments']['Row'],
          'id' | 'created_at' | 'updated_at'
        >;
        Update: Partial<Database['public']['Tables']['payments']['Row']>;
      };
      conversations: {
        Row: {
          id: string;
          booking_id: string | null;
          participant_a: string;
          participant_b: string;
          last_message_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['conversations']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['conversations']['Row']>;
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender_id: string;
          body: string;
          read_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['messages']['Row']>;
      };
      reviews: {
        Row: {
          id: string;
          booking_id: string;
          reviewer_id: string;
          reviewee_id: string;
          rating: number;
          body: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['reviews']['Row'], 'id' | 'created_at'>;
        Update: never;
      };
      artist_documents: {
        Row: {
          id: string;
          artist_id: string;
          doc_type: 'id_front' | 'id_back' | 'selfie';
          storage_path: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['artist_documents']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['artist_documents']['Row']>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          body: string;
          data: Json | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['notifications']['Row']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      price_unit: PriceUnit;
      artist_category: ArtistCategory;
      portfolio_type: PortfolioType;
      booking_status: BookingStatus;
      payment_status: PaymentStatus;
      artist_application_status: ArtistApplicationStatus;
    };
  };
};
